### ISSUE TITLE
Cannot Get Client ID

### ISSUE THREAD

**Issue by cwilli34** [CenterForOpenScience/ember-osf#15]
So whatever was updated most recently has broke our ability to develop further on our own app.  I followed your README.md file and I am assuming that you want me to run the configuration within my own app root folder.  I have created a .yml file in my config directory that has the same name as my computer name "my_computer.yml".  When I try to run the ember server using `BACKEND=stage ember s`, I get a error: `WARNING: No configurations found in configuration directory:/home/username/Documents/Projects//osf-ember-app/ember-osf/config` and a lot of `WARNING: you have specified a backend 'stage' that you have not configured in your config/<hostname>.yml`

The server starts, but when it sends me to the OSF login, I get undefined for client id and the token in the URL, and an error from OSF stating that the client id is a invalid or missing parameter.  

If I run `ember g ember-osf-settings echo $HOSTNAME`, I get an error about `ENOENT: no such file or directory`  and the directory in question is node_modules/node-sass/vendor having , and everything instantly breaks.  No configuration file is even created.  So now in my ember-osf directory I cannot even get the dummy app to run.  In my own app, I can't get past OSF authentication because of the client ID.

**Comment by abought** [comment]
Thanks for the feedback! Three notes may be helpful to you:

1. There is a pending PR that will simplify configuration (#14)
2. The command above requires the backticks to work correctly- you're inserting the result of an [evaluated expression](http://unix.stackexchange.com/questions/27428/what-does-backquote-backtick-mean-in-bash): 
```
ember g ember-osf-settings `echo $HOSTNAME`
```
3. In some cases, we have found the old method has trouble with mixed-case computer names (eg "MyComputer" may write a file named `mycomputer` and fail to load configuration)... hence the updated PR to simplify things. :) You may be able to get it to work by renaming the file to match the hostname more closely, until #14 is merged.

Hope these notes are useful.

**Comment by cwilli34** [comment]
I did use backticks, I just left them out of the above markdown in my comment.  I will try getting it to work with your requirements.

**Comment by cwilli34** [comment]
Ahh, ok.  I renamed the file to all caps and it worked.  And I don't get the errors.  Thanks!
