### ISSUE TITLE
Fix a broken reference in models/node.js

### ISSUE THREAD

**Issue by abrinckm** [CenterForOpenScience/ember-osf#271]
Hi,

I had a problem calling `node.save();` which resulted in this error:

```
TypeError: Cannot read property 'get' of undefined
    at node.js:140
    at Array.filter (<anonymous>)
    at Class.save (node.js:139)
    at Class.superWrapper [as save] (ember.debug.js:45374)
```

I found the culprit in [addons/models/node.js](https://github.com/CenterForOpenScience/ember-osf/blob/develop/addon/models/node.js)
Within the line 
```
contributors.members.list.filter(m => !m.record.get('isNew') ...
```
Where `record` was not found in `m`. However, I did find that `m` contained `_record`.

So my solution was to just change all references of `m.record` to `m._record` and this fixed the issue for me. Not entirely sure if this is a correct solution though.

**Comment by jamescdavis** [comment]
This was recently fixed in #272.

The best way to fix this is to use `m.getRecord()` as `_record` is an internal property.
