### ISSUE TITLE
Better documentation of usage in Ember app

### ISSUE THREAD

**Issue by samchrisinger** [CenterForOpenScience/ember-osf#4]

**Comment by cwilli34** [comment]
So I finally understand that if you just rename or delete the dummy directory that the ember-osf app will no longer point to the dummy app.  I don't know if this is part of broccoli or ember-addons, but now I can get our app working.  So for testing, I just copied the dummy directory and renamed it and all instances to "dashboard".  Everything works, except for when it redirects back to localhost:4200, the "My Nodes" button doesn't work and I get `ember.debug.js:28556Error while processing route: nodes Cannot read property 'get' of null TypeError: Cannot read property 'get' of null`.  I am currently trying to debug this, but if I reload the page or go directly to localhost:4200/nodes, then the nodes load on the page fine.  It just happens at the initial redirect from OSF to http://localhost:4200/login.  How is redirecting handled?  In OSF, it asks for the redirect URL, but if I enter a URL besides http://localhost:4200/login, I get a redirect error when the app tries to go to the OSF login. 

Anyways, that is where I stand now.

**Comment by samchrisinger** [comment]
> Everything works, except for when it redirects back to localhost:4200, the "My Nodes" button doesn't work and I get ember.debug.js:28556Error while processing route: nodes Cannot read property 'get' of null TypeError: Cannot read property 'get' of null. I am currently trying to debug this, but if I reload the page or go directly to localhost:4200/nodes, then the nodes load on the page fine. It just happens at the initial redirect from OSF to http://localhost:4200/login. How is redirecting handled? In OSF, it asks for the redirect URL, but if I enter a URL besides http://localhost:4200/login, I get a redirect error when the app tries to go to the OSF login.

@cwilli34 sorry, this is a known bug. The nodes route is trying to fetch the current user (loaded in the application route's model hook-- `this.modelFor('application')`). Unfortunately the application route's model hook is only run once (when the SPA is first loaded) and there is a slight timing issue between the dummy app's login route (which parses the OAuth token from the query string and "logs in" the user) and when the application route runs. Basically on redirect from the OSF CAS:

ApplicationRoute.model returns null -> LoginRoute parses token and authenticates user -> redirected to index page -> you click "My Nodes", but the ApplicationRoute's model is still null

So when you refresh the page or visit the nodes page directly, the ApplicationRoute is able to correctly fetch the current user. I've been meaning to fix this but it's not my top priority currently. New issue for this here: https://github.com/CenterForOpenScience/ember-osf/issues/5

**Comment by samchrisinger** [comment]
On a side note, I'm doing some refactor of how the addon specifies it's dependencies and will update the README accordingly, which hopefully will make the process of using this addon a bit clearer.

**Comment by samchrisinger** [comment]
@cwilli34 new README pushed. Can you please take a look and see if this is any clearer?

**Comment by cwilli34** [comment]
Hey, thanks Sam. I appreciate it. Maybe it's something we can look into and try fixing it. Now that you explained it thoroughly, it makes sense, and I was kind of getting that idea that it was not fully authenticating until after the redirect happens. I appreciate the explanation, and the documentation is looking great. Sorry for all the questions, but this is my first ember app so it is taking some digging to figure out exactly what the framework is doing. Thanks again.

**Comment by cwilli34** [comment]
Maybe something about deleting the dummy directory would be good when using your own app, and how to change the package.json file to point to the correct config file in the users app. Also, I think you have to replace the name dummy with the name of your app on the config file. I know that information is out there about the dummy, but it took me a while to figure it out, but I wasn't aware of it until I did it on my own.

**Comment by samchrisinger** [comment]
I'm glad this helped some! We definitely understand the learning curve involved here, but I promise it gets better. 

Went ahead and created a full example of using ember-osf inside of a regular Ember app: https://github.com/samchrisinger/ember-osf-demo. Looking at the package.json there might be especially useful (see how it specifies ember-osf as a local dependency?). 

The biggest caveat to this approach is that you'll need to manually pull in changes to ember-osf when we make them. The subtle distinction is that changes made to your local copy of ember-osf will be included automatically. That's why the README says to run `npm link ../ember-osf`; this symlinks the local dependency into your consuming application's node_modules. But when we push changes to the ember-osf repo you will need to do a `git pull origin develop` to grab those changes.

Does this make sense?

**Comment by cwilli34** [comment]
I believe this makes sense, but the example you posted is an ember-app inside of ember-osf, not the symlinked version, correct?

**Comment by samchrisinger** [comment]
No. The example is an Ember app that consumes the ember-osf addon.

Maybe this is another point of confusion. The ember-osf is an _addon_, and is not meant to be a standalone app at all. The dummy app there is just a way to demo and functional test its features.

**Comment by samchrisinger** [comment]
So If you were to:
```bash
git clone git@github.com:CenterForOpenScience/ember-osf.git
git clone git@github.com:samchrisinger/ember-osf-demo.git
cd ember-osf-demo
ember install ../ember-osf
npm link ../ember-osf
npm install && bower install
ember s
```

You'd have an Ember app the is ready to utilize the ember-osf addon

**Comment by cwilli34** [comment]
Great.  I tried that before and it didn't work out so well.  Must of missed one of these steps.  The only weird thing I see is that the .env-stage file has to be in both my app directory and the ember-osf directory, which is redundant.  And you still do have to do ember s --environment staging from within my app.  Not a big deal, but having to have the .env-stage file in both sections doesn't seem right.

Also, this error occurs everytime I run the server: `{ [Error: ENOENT: no such file or directory, open '.env-test'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env-test' }`

Again, not a big deal because the server still runs, but I thought I would make sure you are aware of it, if you aren't. Also, when making the .env file, these errors occur:  

```
{ [Error: ENOENT: no such file or directory, open '.env-undefined']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env-undefined' }
installing env
{ [Error: ENOENT: no such file or directory, open '.env-undefined']
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env-undefined' }
  create .env-test
```

Of course if I create a .env-test file or a .env-undefined file, the errors go away.  So that is probably an easy fix anyway.

**Comment by samchrisinger** [comment]
> The only weird thing I see is that the .env-stage file has to be in both my app directory and the ember-osf directory, which is redundant. And you still do have to do ember s --environment staging from within my app. Not a big deal, but having to have the .env-stage file in both sections doesn't seem right.

I'm having trouble reproducing this. I tried deleting my .env-stage in my copy of ember-osf, but the app still ran fine (it got its settings from the .env-stage file in my copy of ember-osf-demo). Can you please provide steps to reproduce?

> And you still do have to do ember s --environment staging from within my app. Not a big deal, but having to have the .env-stage file in both sections doesn't seem right.

`ember s` defaults to the 'development' environment by default, which in this case corresponds with using a local OSF instance as the backend. Having multiple .env files facilitates rapidly switching between backends. So if you want to use OSF staging as a backend, you will need to pass the `--enviornment staging` flag.

> Also, this error occurs everytime I run the server: { [Error: ENOENT: no such file or directory, open '.env-test'] errno: -2, code: 'ENOENT', syscall: 'open', path: '.env-test' }

This is the dotenv module telling you it can't find a file, you can ignore these errors for now.

**Comment by cwilli34** [comment]
In the documentation:  When you are explaining how to install ember-osf with your own app, there is nothing about bower install for the ember-osf app.  Is that not necessary if you are using your own app?  I still did a bower install in my ember-osf directory anyways, but according to you installation instructions, I literally just clone your repo, do a ember install ../ember-osf, and then npm link ../ember-osf.  Then I run the configuration from within my app directory?  That isn't specific either, but I am assuming that is the case.

**Comment by samchrisinger** [comment]
> When you are explaining how to install ember-osf with your own app, there is nothing about bower install for the ember-osf app. Is that not necessary if you are using your own app?

No. The addon's npm and bower dependencies are installed when `ember install` is run. This is always a hard part in documentation-- we can only assume so much responsibility for explaining the Ember ecosystem in our docs. Do you have any suggestions on how we can make this more clear? PRs welcome!

> Then I run the configuration from within my app directory? That isn't specific either, but I am assuming that is the case.

I'd hoped that since
> generate a settings file (see 'Configuration' below)

is a bullet under 
> From the consuming Ember app:

that this would be clear. Sorry if it wasn't.

**Comment by cwilli34** [comment]
> generate a settings file (see 'Configuration' below)

I assumed this was the case, but since it just says generate a settings file, and then you go to the 'Configuration' section and it doesn't specify, I just had to wonder when it didn't work.  

> No. The addon's npm and bower dependencies are installed when ember install is run. This is always a hard part in documentation-- we can only assume so much responsibility for explaining the Ember ecosystem in our docs. Do you have any suggestions on how we can make this more clear? PRs welcome!

It is obvious that I am new to ember.js with all the questions I have had regarding your repo, so maybe just a little sentence stating that the ember-osf's npm and bower dependencies are installed with the `ember install` command would help new users understand this.  I know you can't go into how ember.js works in your own documentation, but there are basically two sets of instructions for ember-osf: One set is for using with your own stand-alone app, and the other set of instructions for if you are just testing the ember-osf app with the dummy app.  The installation is a little different.  So in the end, I think that is what confused me is whether I still have to install ember-osf separately from my own app, or if everything was taken care of with the `ember install` command.  

Again, a lot of this maybe my own ignorance of ember.js, but I had never even used a bower install before this, only npm.  And since we are using Semantic-UI on our project, trying to understand all the different install processes and configurations involved has been confusing in itself.  So just the more details, the better!  Thank you so much for working on this Sam, and I appreciate the documentation and hard work.

**Comment by cwilli34** [comment]
> Then (using staging as an example) run: BACKEND=test ember server

Shouldn't this be `BACKEND=stage ember server` if "staging" is the example?

**Comment by samchrisinger** [comment]
Thanks for the catch!

**Comment by samchrisinger** [comment]
@cwilli34 I'm closing this in favor of https://github.com/CenterForOpenScience/ember-osf/issues/20 so this ticket doesn't become a catchall. 

Please keep the feedback coming!
