### ISSUE TITLE
Remove Bootstrap Dependencies

### ISSUE THREAD

**Issue by cwilli34** [CenterForOpenScience/ember-osf#8]
This maybe more of a feature request, but I think that all Bootstrap dependencies should be removed.  We are using Semantic-UI in our project and of course they conflict.  There are Bootstrap dependencies in the ember-cli-build.js file and bower.json.  The dummy app really does not need Bootstrap.

**Comment by samchrisinger** [comment]
@cwilli34 these are currently specified as `devDependencies` and are not required for a "production" build. Likewise, the imports in the ember-cli-build are only used for testing with the dummy app: http://ember-cli.com/extending/#addon-ember-cli-build. 

So bootstrap will only be included if you explicitly import it in the consuming app. I just pushed a commit to the ember-osf-demo which removes the bootstrap styles: https://github.com/samchrisinger/ember-osf-demo/commit/c613ad301a1bc23a0a2a120d36007cf08fa7f99a
